[dut]
#conn. settings for k26xx; for GPIB connection use e.g. 'GPIB0::26::INSTR' ; baud and flow are ignored
res = 'ASRL/dev/ttyUSB0::INSTR'
baud = 115200
# flow can be none, rts_cts, xon_xoff see pyvisa.constants.ControlFlow
flow = 'none'

[dmm]
res = 'GPIB0::23::INSTR'

[cal]
 #settling time for all V and low I ranges
step_dwell = 1
#for 3A/10A ranges:
ipulse_ton = 100e-3
#cooldown after 3A/10A
ipulse_toff = 10

#as characterized for 3A/10A ranges
r5_actual = 0.5
# for contact check; not sure if needs measurement (SM just gives 0)
r0_actual = 0
#50r resistor to tie between L and SL (step 4)
r50_l = 50
#50r resistor to tie between H and SH (step 4)
r50_h = 50
