[dut]
#conn. settings for k26xx;
res = 'GPIB0::26::INSTR'
#res = 'ASRL/dev/ttyUSB7::INSTR'
# example for e5810 bridge:
#res = 'TCPIP::192.168.1.12::gpib0,16::INSTR'
#
# baud and flow are ignored on anything other than ASRL resources
baud = 115200
# flow can be none, rts_cts, xon_xoff see pyvisa.constants.ControlFlow
flow = 'none'

[dmm]
driver = 'dmm_xdevs'
res = 'TCPIP::192.168.1.10::gpib0,1::INSTR'
#res = 'GPIB0::23::INSTR'
#res = 'TCPIP::192.168.1.12::gpib0,23::INSTR'

[inl]
# discard a few readings then save the few next for median + stats
discard = 3
keep = 10

# adjust these to fit on same range
sweep_min = -6
sweep_max = 6

step_dwell = 2

# 'linear_n', 'linear_step' or 'random'
spread = 'linear_n'

# step is either total # of points for lin_n and random; or interval for lin_step
step = 9

