[dut]
#conn. settings for k26xx; for GPIB connection use e.g. 'GPIB0::26::INSTR' ; baud and flow are ignored
res = 'ASRL/dev/ttyUSB7::INSTR'
baud = 115200
# flow can be none, rts_cts, xon_xoff see pyvisa.constants.ControlFlow
flow = 'none'

[dmm]
driver = 'dmm_3478'
res = 'GPIB0::23::INSTR'

[inl]
# discard a few readings then save the few next for median + stats
discard = 3
keep = 10

# adjust these to fit on same range
sweep_min = -6
sweep_max = 6

# 'linear_n', 'linear_step' or 'random'
spread = 'linear_n'

# step is either total # of points for lin_n and random; or interval for lin_step
step = 9

