[dut]
#conn. settings for k26xx; for GPIB connection use e.g. 'GPIB0::26::INSTR' ; baud and flow are ignored
res = 'ASRL/dev/ttyUSB0::INSTR'
baud = 115200
# flow can be none, rts_cts, xon_xoff see pyvisa.constants.ControlFlow
flow = 'none'

[dmm]
res = 'GPIB0::23::INSTR'

[pv]
# discard a few readings then save the few next for median + stats
discard_v = 2
keep_v = 3

discard_i = 2
keep_i = 3

#default settling time for all V and low I ranges
step_dwell = 2
#for 3A ranges:
ipulse_ton = 100e-3
#cooldown after 3A
ipulse_toff = 1

#per-range settling times; optional
dly_100mA = 2
dly_1A = 3

#as characterized for 3A range
r5_actual = 0.5
